import Foundation

struct StoryboardId {
    static let OTPHandlingViewController = "OTPHandlingViewController"
    static let SignUpViewController = "SignUpViewController"
    static let LoginViewController = "LoginViewController"
    static let LoginNavViewController = "LoginNavViewController"
    static let HomeNavViewController = "HomeNavViewController"
    static let TnCViewController = "TnCViewController"
    static let DashBoardViewController = "DashBoardViewController"
    static let DashBoardNavViewController = "DashBoardNavViewController"
    static let PasswordRecoveryVC = "PasswordRecoveryViewController"
    static let CreateNewPasswordVC = "CreateNewPasswordViewController"
    static let PasswordSuccessVC = "PasswordSuccessViewController"
    static let NotificationViewController = "NotificationViewController"
    static let AcceptMobileNumberViewController = "AcceptMobileNumberViewController"
    static let EnterPinViewController = "EnterPinViewController"
    static let ConformPINViewController = "ConformPINViewController"
    static let BiometricsViewController = "BiometricsViewController"
    static let MyInfoWebViewController = "MyInfoWebViewController"
    static let MyInfoViewController = "MyInfoViewController"
    static let NotificationSuccessViewController = "NotificationSuccessViewController"
    static let TipsViewController = "TipsViewController"
    static let WalletLoginViewController = "WalletLoginViewController"
    static let PlaylistViewController = "PlaylistViewController"
    static let EditPlaylistFieldViewController = "EditPlaylistViewController"
    static let VenueDetailsViewController = "VenueDetailsViewController"
    static let MyInfoDetailsViewController = "MyInfoDetailsViewController"
    static let CurrentPinViewController = "CurrentPinViewController"
    static let ManageWalletViewController = "ManageWalletViewController"
    static let NotificationCustomViewController = "NotificationCustomViewController"
    static let ManageWalletNavViewController = "ManageWalletNavViewController"
    static let TNCForWalletViewController =  "TNCForWalletViewController"
    static let TopUpQRCodeViewController = "TopUpQRCodeViewController"
    static let YourLikesViewController = "YourLikesViewController"
    static let PaymentDetailViewController = "PaymentDetailViewController"
    static let TopUpNavViewController = "TopUpNavViewController"
    static let TopUpAmountViewController = "TopUpAmountViewController"
    static let CardPaymentViewController = "CardPaymentViewController"
    static let WithdrawNavViewController = "WithdrawNavViewController"
    static let WithdrawAmountViewController = "WithdrawAmountViewController"
    static let BankAccountViewController = "BankAccountViewController"
    static let StripeUIWebviewViewController = "StripeUIWebviewViewController"
    static let AllPlacesViewController = "AllPlacesViewController"
    static let SearchViewController = "SearchViewController"
    static let WithDrawConfirmationViewController = "WithDrawConfirmationViewController"
}

struct StoryboardName {
    static let Main = "Main"
    static let Verification = "Verification"
    static let Login = "Login"
    static let RegisterWihEmail = "RegisterWihEmail"
    static let Dashboard = "Dashboard"
    static let WalletFlow = "WalletFlow"
    static let Biometrics = "Biometrics"
    static let MyInfo = "MyInfo"
    static let Notification = "Notifications"
    static let TabBar = "TabBar"
    static let WalletLogin = "WalletLogin"
    static let Playlist = "Playlist"
    static let TnC = "TnC"
    static let CurrentPin = "CurrentPIN"
    static let ManageWallet = "ManageWallet"
    static let TopUp = "TopUP"
    static let CardPayment = "CardPayment"
    static let Discovery = "Discovery"
    static let Withdraw = "Withdraw"
    static let BankAccount = "BankAccount"
    static let Common = "Common"
    static let StripeWebView = "StripeWebView"
    static let Search = "Search"
}
